IP_ADDRESS = "192.168.1.151"
PORT = 9990
TIMEOUT_SECONDS = 5

ROUTING = {
    "camera": {
        "OUTPUT_CHANNELS": 1,
        "INPUT_CHANNELS": 1,
    },
    "hdmi": {
        "OUTPUT_CHANNELS": 1,
        "INPUT_CHANNELS": 2,
    },
}

PIN_FOR_CHANGE_TO_CAMERA = 14
PIN_FOR_CHANGE_TO_HDMI = 15
